### ISSUE TITLE
IllegalArgumentException: Receiver not registered

### ISSUE THREAD

**Issue by symphonybiz** [livekit/client-sdk-android#128]
**Describe the bug**
We detected the following crash in production, through our crash reporting system. Unfortunately we don't have repro steps.

```
Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: s8.b@9017346
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1523)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1712)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:733)
       at com.twilio.audioswitch.wired.WiredHeadsetReceiver.stop(WiredHeadsetReceiver.kt:45)
       at com.twilio.audioswitch.AudioSwitch.closeListeners(AudioSwitch.kt:362)
       at com.twilio.audioswitch.AudioSwitch.stop(AudioSwitch.kt:180)
       at io.livekit.android.audio.AudioSwitchHandler.stop(AudioSwitchHandler.kt:37)
       at io.livekit.android.room.Room$state$2.invoke(Room.kt:86)
       at io.livekit.android.room.Room$state$2.invoke(Room.kt:82)
       at io.livekit.android.util.MutableStateFlowDelegate.setValue(FlowDelegate.kt:90)
       at io.livekit.android.room.Room.c0(Room.kt:7)
       at io.livekit.android.room.Room.handleDisconnect(Room.kt:448)
       at io.livekit.android.room.Room.onEngineDisconnected(Room.kt:695)
       at io.livekit.android.room.RTCEngine.onLeave(RTCEngine.kt:691)
       at io.livekit.android.room.SignalClient.handleSignalResponseImpl(SignalClient.kt:514)
       at io.livekit.android.room.SignalClient.access$sendRequestImpl(SignalClient.kt:36)
       at io.livekit.android.room.SignalClient$onReadyForResponses$1$1.emit(SignalClient.kt:167)
       at io.livekit.android.room.SignalClient$onReadyForResponses$1$1.emit(SignalClient.kt:165)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Device Info:**
 - Device: Motorola, Samsung, Xiaomi, LGE, Others
 - OS: Android 7 to Android 12
 - LiveKit SDK version: `io.livekit:livekit-android:1.1.0`

**Comment by davidliu** [comment]
Hey @symphonybiz, this should be fixed in 1.1.1. There was a race condition that was addressed in that release.

**Comment by symphonybiz** [comment]
@davidliu does the same apply to this?

```
Fatal Exception: kotlin.UninitializedPropertyAccessException: publisher has not been initialized yet.
       at io.livekit.android.room.RTCEngine.getPublisher$livekit_android_sdk_release(RTCEngine.kt:96)
       at io.livekit.android.room.RTCEngine.onTrickle(RTCEngine.kt:634)
       at io.livekit.android.room.SignalClient.handleSignalResponseImpl(SignalClient.kt:499)
       at io.livekit.android.room.SignalClient.access$sendRequestImpl(SignalClient.kt:36)
       at io.livekit.android.room.SignalClient$onReadyForResponses$1$1.emit(SignalClient.kt:167)
       at io.livekit.android.room.SignalClient$onReadyForResponses$1$1.emit(SignalClient.kt:165)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by davidliu** [comment]
That's a separate issue, please file a separate issue for that.

**Comment by symphonybiz** [comment]
ok thanks!
