### ISSUE TITLE
Fatal Exception: kotlin.UninitializedPropertyAccessException: publisher has not been initialized yet

### ISSUE THREAD

**Issue by symphonybiz** [livekit/client-sdk-android#129]
**Describe the bug**
We detected the following crash in production, through our crash reporting system. Unfortunately we don't have repro steps.

```
Fatal Exception: kotlin.UninitializedPropertyAccessException: publisher has not been initialized yet.
       at io.livekit.android.room.RTCEngine.getPublisher$livekit_android_sdk_release(RTCEngine.kt:96)
       at io.livekit.android.room.RTCEngine.onTrickle(RTCEngine.kt:634)
       at io.livekit.android.room.SignalClient.handleSignalResponseImpl(SignalClient.kt:499)
       at io.livekit.android.room.SignalClient.access$sendRequestImpl(SignalClient.kt:36)
       at io.livekit.android.room.SignalClient$onReadyForResponses$1$1.emit(SignalClient.kt:167)
       at io.livekit.android.room.SignalClient$onReadyForResponses$1$1.emit(SignalClient.kt:165)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Device Info:**
 - Device: Samsung, Motorola, Xiaomi, LGE, Others
 - OS: Android 7 to Android 12
 - LiveKit SDK version: `io.livekit:livekit-android:1.1.0`

**Comment by symphonybiz** [comment]
It probably related to this one? https://github.com/livekit/client-sdk-android/issues/110
