### ISSUE TITLE
IllegalArgumentException: Receiver not registered: com.twilio.audioswitch.wired.WiredHeadsetReceiver

### ISSUE THREAD

**Issue by symphonybiz** [livekit/client-sdk-android#133]
**Describe the bug**
We got the following crash:

```
2022-08-16 08:49:04.973 10854-15268/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.jaumo, PID: 10854
    java.lang.IllegalArgumentException: Receiver not registered: com.twilio.audioswitch.wired.WiredHeadsetReceiver@a51e4e8
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1439)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
        at com.twilio.audioswitch.wired.WiredHeadsetReceiver.stop(WiredHeadsetReceiver.kt:45)
        at com.twilio.audioswitch.AudioSwitch.closeListeners(AudioSwitch.kt:362)
        at com.twilio.audioswitch.AudioSwitch.stop(AudioSwitch.kt:180)
        at io.livekit.android.audio.AudioSwitchHandler.stop(AudioSwitchHandler.kt:37)
        at io.livekit.android.room.Room$state$2.invoke(Room.kt:86)
        at io.livekit.android.room.Room$state$2.invoke(Room.kt:82)
        at io.livekit.android.util.MutableStateFlowDelegate.setValue(FlowDelegate.kt:90)
        at io.livekit.android.room.Room.setState(Room.kt:82)
        at io.livekit.android.room.Room.handleDisconnect(Room.kt:448)
        at io.livekit.android.room.Room.onEngineDisconnected(Room.kt:695)
        at io.livekit.android.room.RTCEngine.onLeave(RTCEngine.kt:691)
        at io.livekit.android.room.SignalClient.handleSignalResponseImpl(SignalClient.kt:514)
        at io.livekit.android.room.SignalClient.access$handleSignalResponseImpl(SignalClient.kt:36)
        at io.livekit.android.room.SignalClient$onReadyForResponses$1$1.emit(SignalClient.kt:167)
        at io.livekit.android.room.SignalClient$onReadyForResponses$1$1.emit(SignalClient.kt:165)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d8e94c1, Dispatchers.IO]
```

**To Reproduce**
Unfortunately we don't have repro steps

**Device Info:**
 - Device: Xiaomi Mi 10
 - OS: Android 12
 - LiveKit SDK version: 1.1.1

**Comment by davidliu** [comment]
Hey, @symphonybiz, can you recheck the LiveKit SDK version? The line numbers and stack trace seems to indicate this is 1.1.0, prior to the fix for this issue.

**Comment by symphonybiz** [comment]
You are right @davidliu , it was actually `1.1.0`. Closing this issue, thanks
