### ISSUE TITLE
Flip camera error

### ISSUE THREAD

**Issue by vincentbrison** [livekit/client-sdk-android#145]
**Describe the bug**
When flipping the camera using exactly same code as in the sample https://github.com/livekit/client-sdk-android/blob/e6c9d9b7054b304b2d9b87739da139b32a8a5e02/sample-app-common/src/main/java/io/livekit/android/sample/CallViewModel.kt#L229-L241, the device camera is crashing and is unusable, even by other apps, until full device reboot.

**To Reproduce**
1. Flip camera few times (usually 2 to 5 times)

**Expected behavior**
Flipping the camera should not crash the camera, nor retain a lock on it, preventing other apps to use it.

**Device Info:**
 - Device: Samsung S10e
 - OS: Android 12
 - LiveKit SDK version: [e.g. 1.1.3]

**Additional context**
Cannot reproduce on emulator using Android 12. It's probably hardware specific, but it should at least fail gracefully? Here are the logs:

```
2022-09-20 15:05:31.448 11886-13713/com.nabla.sdk.playground.dev I/CameraManagerGlobal: Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.nabla.sdk.playground.dev API Level 2
2022-09-20 15:05:31.496 11886-13713/com.nabla.sdk.playground.dev I/CameraManagerGlobal: Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.nabla.sdk.playground.dev API Level 2
2022-09-20 15:05:31.547 11886-11904/com.nabla.sdk.playground.dev I/CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_IDLE for client com.nabla.sdk.playground.dev API Level 2
2022-09-20 15:05:31.626 11886-13713/com.nabla.sdk.playground.dev I/CameraManagerGlobal: Camera 0 facing CAMERA_FACING_BACK state now CAMERA_STATE_CLOSED for client com.nabla.sdk.playground.dev API Level 2
2022-09-20 15:05:31.627 11886-11908/com.nabla.sdk.playground.dev W/.playground.de: Long monitor contention with owner VideoCaptureThread (29105) at void android.hardware.camera2.impl.CameraDeviceImpl.close()(CameraDeviceImpl.java:1400) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onResultReceived(android.hardware.camera2.impl.CameraMetadataNative, android.hardware.camera2.impl.CaptureResultExtras, android.hardware.camera2.impl.PhysicalCaptureResultInfo[]) for 204ms
2022-09-20 15:05:32.457 11886-29218/com.nabla.sdk.playground.dev I/MediaCodec: setCodecState state(0), called in 6
2022-09-20 15:05:33.218 11886-29193/com.nabla.sdk.playground.dev I/MediaCodec: setCodecState state(0), called in 6
2022-09-20 15:05:33.305 11886-29206/com.nabla.sdk.playground.dev I/MediaCodec: setCodecState state(0), called in 6
2022-09-20 15:05:35.219 11886-29262/com.nabla.sdk.playground.dev E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2378)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1305)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
        at org.webrtc.Camera2Session.stopInternal(Camera2Session.java:384)
        at org.webrtc.Camera2Session.reportError(Camera2Session.java:405)
        at org.webrtc.Camera2Session.access$600(Camera2Session.java:31)
        at org.webrtc.Camera2Session$CameraStateCallback.onError(Camera2Session.java:110)
        at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1776)
        at android.hardware.camera2.impl.CameraDeviceImpl.$r8$lambda$KBQCqQRdhVVn7uHI9Xdha6OqnsU(Unknown Source:0)
        at android.hardware.camera2.impl.CameraDeviceImpl$$ExternalSyntheticLambda0.accept(Unknown Source:8)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

I can produce more detailed logs if needed. Thanks!

**Comment by vincentbrison** [comment]
Adding that flipping the camera in other web call apps on the same device has no issue (Signal and Slack were tested)

**Comment by vincentbrison** [comment]
I may found a workaround on this issue. The idea is to ensure, when flipping camera, that the previous one is shut before open the new one. So instead of calling `videoTrack.restartTrack(newOptions)`, I do the following:

```kotlin
videoTrack.stopCapture()

val cameraManager = application.getSystemService(CameraManager::class.java)
val cameraIdList = cameraManager.cameraIdList.toMutableList()

suspendCancellableCoroutine<Unit> { cancellableContinuation ->
    val callback =
        object : CameraManager.AvailabilityCallback() {
            override fun onCameraAvailable(cameraId: String) {
                super.onCameraAvailable(cameraId)
                cameraIdList.remove(cameraId)
                if (cameraIdList.isEmpty()) {
                    cameraManager.unregisterAvailabilityCallback(this)
                    cancellableContinuation.resume(Unit)
                }
            }
        }

    cancellableContinuation.invokeOnCancellation {
        cameraManager.unregisterAvailabilityCallback(callback)
    }

    cameraManager.registerAvailabilityCallback(callback, null)
}

videoTrack.restartTrack(newOptions)
```

This code is wrapped in a coroutine, with debouncing strategy to avoid spamming concurrent flips as it is triggered by UI action.

**Comment by davidliu** [comment]
When it gets into this state, does force stopping the app fix the camera for other apps? Or still permanent until reset?

How fast are you flipping? Is this human taps or programmatically repeated flipping?

**Comment by vincentbrison** [comment]
Force stopping does nothing. The camera is still locked, and no app, even the native camera app of the phone can use it. The only solution is to reboot the phone.

> How fast are you flipping?
By hand, and it can happen by flipping once every 10 seconds. We already debounced the flip click. It looks like the real issue if opening another camera without waiting the previous one to be shutdown, so it only needs one flip to happen (which we already observed).

**Comment by davidliu** [comment]
Interesting. Does it seem to only happen on this particular phone? 

Also, I'm guessing that means that if two cameras are opened at the same time for this particular phone, it'll get into this bad state?

**Comment by vincentbrison** [comment]
I only have a Nexus 6P and a Samsung S10e as physical devices, so as far as I am concerned, yes it only happens on this particular phone, but I would not be surprise if it would happen on other phones of the same brand. BTW it does not look as a hardware defect, as other third party apps like Signal, or WhatsApp have no issue at all flipping the cameras during call on this phone.

From the workaround, and the error observed, yes, it looks like it does not like at all having two cameras opened at the same time through camera2 API. I wonder if it would be the same using [camerax APIs](https://developer.android.com/training/camerax).

**Comment by davidliu** [comment]
IIRC, CameraX is a convenience wrapper around Camera2, so probably won't change much.

I'll check against Signal's implementation and see if there's anything there we can glean from it.

**Comment by vincentbrison** [comment]
> IIRC, CameraX is a convenience wrapper around Camera2, so probably won't change much.

It is based on Camera2 but it looks like it does [a lot more](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-main/camera?source=post_page---------------------------%2F%2F%2F%2F&autodive=0). In particular their implementation is tested against a broad range of [devices](https://developer.android.com/training/camerax/devices).

**Comment by davidliu** [comment]
Looks like there's an alternate method in WebRTC for switching cameras, I'll put up a fix for this; will likely be a new method on `LocalTrack` for doing this.

**Comment by davidliu** [comment]
A new `switchCamera` method has been added to `LocalTrack`. You can pass in a deviceId or cameraPosition to specify which one to use.

See the example app for usage:

https://github.com/livekit/client-sdk-android/blob/main/sample-app-common/src/main/java/io/livekit/android/sample/CallViewModel.kt#L245
