### ISSUE TITLE
Crash when flipping camera too fast

### ISSUE THREAD

**Issue by benoitletondor** [livekit/client-sdk-android#147]
**Describe the bug**
When flipping the cameras too fast on Pixel 6 Pro I end up with a crash

**To Reproduce**
1. Flip camera super quick like 10 times

**Expected behavior**
No crash

**Device Info:**
 - Device: Pixel 6 Pro
 - OS: Android 13
 - LiveKit SDK version: `io.livekit:livekit-android:1.1.1`

**Additional context**

Crash log:

```
FATAL EXCEPTION: main
                                                                                                    Process: xxx, PID: 28272
                                                                                                    kotlin.NotImplementedError: An operation is not implemented.
                                                                                                    	at io.livekit.android.room.track.LocalVideoTrack$Companion.createTrack$livekit_android_sdk_release(LocalVideoTrack.kt:169)
                                                                                                    	at io.livekit.android.room.track.LocalVideoTrack.restartTrack(LocalVideoTrack.kt:81)
                                                                                                    	at xxx$onFlipCameraClicked$1.invokeSuspend(VideoCallViewModel.kt:229)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
                                                                                                    	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
                                                                                                    	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
                                                                                                    	at xxx$awaitAllCamerasAvailable$2$callback$1.onCameraAvailable(VideoCallViewModel.kt:248)
                                                                                                    	at android.hardware.camera2.CameraManager$CameraManagerGlobal$6.run(CameraManager.java:2093)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@fbd1c9c, Dispatchers.Main.immediate]
```

Crash happens here: https://github.com/livekit/client-sdk-android/blob/1a053234f089e16b8f17e0e1c1d3b6c8e966bc0b/livekit-android-sdk/src/main/java/io/livekit/android/room/track/LocalVideoTrack.kt#L169

**Comment by davidliu** [comment]
Are there any logs prior to the crash indicating anything about the camera status?

**Comment by benoitletondor** [comment]
Nope didn't get anything particular, sorry

**Comment by benoitletondor** [comment]
I'm really unsure #149 really makes sure the crash won't happen. The `TODO()` that led to the crash is still in the code: https://github.com/livekit/client-sdk-android/blob/main/livekit-android-sdk/src/main/java/io/livekit/android/room/track/LocalVideoTrack.kt#L223

**Comment by davidliu** [comment]
SwitchCamera uses a different code path that won't run into that issue.

**Comment by davidliu** [comment]
switchCamera should be used instead of restartTrack, so that code path
won't be hit.
