### ISSUE TITLE
End call crash  (v1.1.4)

### ISSUE THREAD

**Issue by Arm63** [livekit/client-sdk-android#159]
**Describe the bug**

On version, 1.1.4 try to end calls with the calling room.disconnect(), the crash is happens

Create room in ViewModel
    val audioHandler = AudioSwitchHandler(app)
    val room = LiveKit.create(
        appContext = app,
        options = RoomOptions(adaptiveStream = true, dynacast = true),
        overrides = LiveKitOverrides(
            audioHandler = audioHandler
        )
    )

1. Start a call
2. Waiting until UI is loaded
3. End a call, with calling (room.disconnect())   <--Crash step

**Expected behavior**
Call must end

**Device Info:**
 - Device: [Google Pixel 2]
 - OS: [Android 11]
 - LiveKit SDK version: [1.1.4]
 
   kotlin.UninitializedPropertyAccessException: publisher has not been initialized yet.
                                         	at io.livekit.android.room.RTCEngine.getPublisher$livekit_android_sdk_release(RTCEngine.kt:98)
                                         	at io.livekit.android.room.participant.LocalParticipant.unpublishTrack(LocalParticipant.kt:413)
                                         	at io.livekit.android.room.participant.LocalParticipant.unpublishTrack$default(LocalParticipant.kt:402)
                                         	at io.livekit.android.room.participant.LocalParticipant.cleanup(LocalParticipant.kt:566)
                                         	at io.livekit.android.room.Room.cleanupRoom(Room.kt:446)
                                         	at io.livekit.android.room.Room.handleDisconnect(Room.kt:465)
                                         	at io.livekit.android.room.Room.disconnect(Room.kt:248)
                                         	at -------------LiveKitCallViewModel.disconnect(LiveKitCallViewModel.kt:321)

**Comment by davidliu** [comment]
Looks like there's a race condition here with the RTCEngine processing a leave message while Room.disconnect() is called. This might take some time to fix.

In the meantime, I think reversing the order might be a workaround (disconnecting the room object before deleting the room from the server).

**Comment by benoitletondor** [comment]
Hey, any news on that @davidliu ?

**Comment by davidliu** [comment]
Hey @benoitletondor, no news at the moment, I'll take another look at fixing this soon though.

**Comment by shimika** [comment]
Is it fixed in latest version? @davidliu

**Comment by usayplz** [comment]
have same bug, it happens when I try to execute room.disconnect immediately after I'v got Room.State.CONNECTED

**Comment by gao746700783** [comment]
mark
