### ISSUE TITLE
MediaStreamTrack has been disposed!

### ISSUE THREAD

**Issue by mohsen2986** [livekit/client-sdk-android#236]
**we got huge crash error on MediaStreamTrack has been disposed!**
our crash reporter , record big number of crash on VideoTrack.
i dont know how it produce :(

here is reported logs:

`
java.lang.IllegalStateException: MediaStreamTrack has been disposed.
	at org.webrtc.MediaStreamTrack.checkMediaStreamTrackExists(MediaStreamTrack.java:13)
	at org.webrtc.MediaStreamTrack.getNativeMediaStreamTrack(MediaStreamTrack.java)
	at org.webrtc.VideoTrack.addSink(VideoTrack.java:23)
	at io.livekit.android.room.track.VideoTrack.addRenderer(VideoTrack.java:14)
	at io.livekit.android.compose.VideoRendererKt.VideoRenderer$setupVideoIfNeeded(VideoRendererKt.java:27)
	at io.livekit.android.compose.VideoRendererKt.access$VideoRenderer$setupVideoIfNeeded(VideoRendererKt.java)
	at io.livekit.android.compose.VideoRendererKt$VideoRenderer$4.invoke(VideoRendererKt$VideoRenderer.java:23)
	at io.livekit.android.compose.VideoRendererKt$VideoRenderer$4.invoke(VideoRendererKt$VideoRenderer.java:2)
	at androidx.compose.ui.viewinterop.ViewFactoryHolder.setFactory(ViewFactoryHolder.java:13)
	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$1.invoke(AndroidView_androidKt$AndroidView.java:13)
	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$1.invoke(AndroidView_androidKt$AndroidView.java)
	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$$inlined$ComposeNode$1.invoke(AndroidView_androidKt$AndroidView$$inlined$ComposeNode.java:2)
	at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(ComposerImpl$createNode.java:17)
	at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(ComposerImpl$createNode.java:6)
	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(ComposerImpl$recordInsert.java:36)
	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(ComposerImpl$recordInsert.java:6)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(CompositionImpl.java:60)
	at androidx.compose.runtime.CompositionImpl.applyChanges(CompositionImpl.java:5)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer$runRecomposeAndApplyChanges$2.java:174)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer$runRecomposeAndApplyChanges$2.java:6)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock$withFrameNanos$2$callback.java:10)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.java:33)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.java)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher$dispatchCallback.java:16)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:994)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException
`

**Comment by davidliu** [comment]
Hmm, sounds like you're attaching a track beyond its lifecycle. Not sure if there's anything we can do on our end to fix this. Make sure you're not holding on to tracks locally and attempting to attach them when they're no longer valid.

**Comment by davidzhao** [comment]
@gerasanchit Please file a new issue with detailed repro steps.

**Comment by gerasanchit** [comment]
hi @davidzhao already added here https://github.com/livekit/client-sdk-android/issues/442

**Comment by davidzhao** [comment]
Thanks @gerasanchit
