### ISSUE TITLE
PeerConnection

### ISSUE THREAD

**Issue by hoale90** [livekit/client-sdk-android#406]
**Crash**
When try to disconnect room, i got a crash. The crashlog that i got. Any idea for it? 

Non-fatal Exception: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'void livekit.org.webrtc.RtpTransceiver.dispose()' on a null object reference
       at java.util.concurrent.FutureTask.report(FutureTask.java:123)
       at java.util.concurrent.FutureTask.get(FutureTask.java:193)
       at mh.d.a(SourceFile:40)
       at dh.c1.b(SourceFile:78)
       at dh.w1.j(SourceFile:1714)
       at dh.q1.a(SourceFile:18)
       at fj.h0.m(SourceFile:168)
       at fj.g0.invokeSuspend(:12)
       at mi.a.resumeWith(:8)
       at cj.g0.run(:107)
       at c7.n.run(SourceFile:15)
       at jj.i.run(:2)
       at jj.a.run(SourceFile:94)

**Comment by davidzhao** [comment]
please retest on latest version
