### ISSUE TITLE
lateinit property localParticipant has not been initialized

### ISSUE THREAD

**Issue by jarvislin** [livekit/client-sdk-android#44]
Hi,

I integrated this SDK (`0.8.0`) and copy the code snippet from the README.md.
But it always crash when my device handle the connection for the first time.
The code snippet works well after the crash, it won't crash again in short time (maybe 3 mins).

This crash happens to my devices:
Samsung A30s, Android 10
Samsung A70, Android 9
Pixel 3a, Android 11
Vivo Y20, Android 10
Vivo Y15, Android 9

Here is the stack trace:
```
kotlin.UninitializedPropertyAccessException: lateinit property localParticipant has not been initialized
        at io.livekit.android.room.Room.getLocalParticipant(Room.kt:120)
        at io.livekit.android.room.Room.getParticipant(Room.kt:195)
        at io.livekit.android.room.Room.onConnectionQuality(Room.kt:455)
        at io.livekit.android.room.RTCEngine.onConnectionQuality(RTCEngine.kt:537)
        at io.livekit.android.room.SignalClient.handleSignalResponseImpl(SignalClient.kt:439)
        at io.livekit.android.room.SignalClient.access$handleSignalResponseImpl(SignalClient.kt:36)
        at io.livekit.android.room.SignalClient$onReady$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:136)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:372)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect(Unknown Source:0)
        at io.livekit.android.room.SignalClient$onReady$1.invokeSuspend(SignalClient.kt:505)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
I also record my screen:
https://imgur.com/a/9CGuLHB

In this video, I called
```
launch {
        room = LiveKit.connect(...)
}
```
in `onCreate()` after I clicked the button, then I got a crash.
But after relaunch my app, it didn't trigger the crash again.

**Comment by davidliu** [comment]
Should be resolved by https://github.com/livekit/client-sdk-android/pull/45.

**Comment by jarvislin** [comment]
Thanks for your reply.
I'll test again by using the latest main branch.

**Comment by jarvislin** [comment]
The latest commit on main branch works like a charm 🚀
Thank you.
