### ISSUE TITLE
运行最新的demo报SSL错误

### ISSUE THREAD

**Issue by mengxiabing** [livekit/client-sdk-android#460]
运行最新的demo，无法连接服务器，报SSL错误
2024-07-24 16:19:21.514 23291-23362 SignalClient            io.livekit.android                   V  Closing SignalClient: code = 1000, reason = Starting new connection
                                                                                                    java.lang.Exception
                                                                                                    	at io.livekit.android.room.SignalClient.close(SignalClient.kt:774)
                                                                                                    	at io.livekit.android.room.SignalClient.close$default(SignalClient.kt:773)
                                                                                                    	at io.livekit.android.room.SignalClient.connect(SignalClient.kt:148)
                                                                                                    	at io.livekit.android.room.SignalClient.join(SignalClient.kt:119)
                                                                                                    	at io.livekit.android.room.RTCEngine$joinImpl$2.invokeSuspend(RTCEngine.kt:192)
                                                                                                    	at io.livekit.android.room.RTCEngine$joinImpl$2.invoke(Unknown Source:8)
                                                                                                    	at io.livekit.android.room.RTCEngine$joinImpl$2.invoke(Unknown Source:4)
                                                                                                    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
                                                                                                    	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
                                                                                                    	at io.livekit.android.room.RTCEngine.joinImpl(RTCEngine.kt:191)
                                                                                                    	at io.livekit.android.room.RTCEngine.join(RTCEngine.kt:183)
                                                                                                    	at io.livekit.android.room.Room$connect$2$connectJob$1.invokeSuspend(Room.kt:383)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-07-24 16:19:21.529 23291-23291 WindowClient            io.livekit.android                   D  Add to mViews: DecorView@76e8a87[CallActivity], this = android.view.WindowManagerGlobal@bac6a64mViews.size()=2
2024-07-24 16:19:21.529 23291-23291 WindowClient            io.livekit.android                   D  Add to mViews packageName:io.livekit.android
2024-07-24 16:19:21.530 23291-23291 ViewRootImpl            io.livekit.android                   I  startAppTraversalsAccelerate mBasePackageName = io.livekit.android ,isEnableAppTraversalsAccelerate = false
2024-07-24 16:19:21.534 23291-23362 SignalClient            io.livekit.android                   I  connecting to wss://172.16.20.86:24529/rtc?access_token=eyJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiR0siLCJ2aWRlbyI6eyJyb29tIjoiMTIzNDU2Iiwicm9vbUpvaW4iOnRydWUsImNhblB1Ymxpc2giOnRydWUsImNhblB1Ymxpc2hEYXRhIjp0cnVlLCJjYW5TdWJzY3JpYmUiOnRydWV9LCJpc3MiOiJkeHl0IiwiZXhwIjoxNzIxNzIzMTUwLCJuYmYiOjAsInN1YiI6IkdLIn0.tH3B5HUhEuzT6JrOLp9j6T6sVvnrqzpF9YjiMvBOBQ0&protocol=12&auto_subscribe=1&adaptive_stream=1&sdk=android&version=2.4.0-SNAPSHOT&device_model=ZTE ZTE A2022H&os=android&os_version=11&network=wifi
2024-07-24 16:19:21.537 23291-23291 AudioManager            io.livekit.android                   I  In isSpeakerphoneOn(), calling application: io.livekit.android
2024-07-24 16:19:21.537 23291-23291 AudioManager            io.livekit.android                   I  isSpeakerphoneOn mSpkrStatus false
2024-07-24 16:19:21.684 23291-23291 AudioManager            io.livekit.android                   I  In setSpeakerphoneOn(), on: false, calling application: io.livekit.android
2024-07-24 16:19:21.685 23291-23291 AudioManager            io.livekit.android                   I  In stopBluetoothSco(), calling application: io.livekit.android
2024-07-24 16:19:22.067 23291-23291 Choreographer           io.livekit.android                   D  tcd updateAppVisible:true
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  failed to validate connection
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2024-07-24 16:19:22.378 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at io.livekit.android.room.SignalClient.onFailure(SignalClient.kt:298)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:592)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.ws.RealWebSocket$connect$1.onFailure(RealWebSocket.kt:202)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at java.lang.Thread.run(Thread.java:923)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:677)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	... 31 more
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	... 45 more
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  websocket failure: null
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at java.lang.Thread.run(Thread.java:923)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:677)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
2024-07-24 16:19:22.379 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
2024-07-24 16:19:22.380 23291-23381 SignalClient            io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
2024-07-24 16:19:22.380 23291-23381 SignalClient            io.livekit.android                   E  	... 27 more
2024-07-24 16:19:22.380 23291-23381 SignalClient            io.livekit.android                   E  Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.380 23291-23381 SignalClient            io.livekit.android                   E  	... 41 more
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at java.lang.Thread.run(Thread.java:923)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:677)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	... 27 more
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-07-24 16:19:22.382 23291-23291 CallViewModel           io.livekit.android                   E  	... 41 more

**Comment by davidliu** [comment]
Looks like you don't have a proper cert signed by a trusted authority. Test your server against https://www.digicert.com/help/

If you're just testing against a local server without certificates, use `ws://` as the protocol instead of `wss://`.
