### ISSUE TITLE
Deadlock caused by multiple camera capturers

### ISSUE THREAD

**Issue by davidliu** [livekit/client-sdk-android#471]
Hi guys, we're using LiveKit SDK in Android and encountered a `deadlock` which leads to `ANR`. We can reproduce this with 100% frequency.
The case is when we disconnect a room (via `room?.disconnect()` ) with `setCameraEnabled(true)` on local participant.

I think there's already a similar issue reported here: <https://github.com/livekit/client-sdk-android/issues/450>
with same stacktrace.

Since we can reproduce this issue with 100% frequency, please let me know if you need any kind of log for further analysis.

From my point of view, the `deadlock` comes from the reason that: `disconnect` method and `CameraCapturer.stopCapture` are synchronizing  on the same lock object `stateLock`  object.

Could you please help taking a look? cc <@U01NZKTNE1H>
Thanks.

PS: Livekit version is 2.6.0.

[Slack Message](https://livekit-users.slack.com/archives/C025KM0S1CK/p1723089198895049?thread_ts=1723089198.895049&cid=C025KM0S1CK)

**Comment by davidliu** [comment]
Seems to be caused by multiple camera capturers created by `setCameraEnabled(true)` when the publication hasn't been created yet.

**Comment by tuan-jason** [comment]
@davidliu I think the issue still persists. 
Could you please take a look?
I'm using LiveKit version `2.9.0`.
Below is the stack trace of the ANR:

```
DALVIK THREADS (212):
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x72f94ab0 self=0xb400007abbced380
  | sysTid=15843 nice=-10 cgrp=default sched=1073741824/0 handle=0x7b858add18
  | state=S schedstat=( 22202049960 834358161 46835 ) utm=1864 stm=355 core=0 HZ=100
  | stack=0x7fe63e9000-0x7fe63eb000 stackSize=8188KB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x05580c51> (a java.lang.Object)
  at java.lang.Object.wait(Object.java:405)
  at java.lang.Object.wait(Object.java:543)
  at livekit.org.webrtc.CameraCapturer.stopCapture(CameraCapturer.java:286)
  - locked <0x05580c51> (a java.lang.Object)
  at livekit.org.webrtc.Camera2Capturer.stopCapture(Camera2Capturer.java:17)
  at io.livekit.android.room.track.video.Camera2CapturerWithSize.stopCapture(unavailable:2)
  at io.livekit.android.room.track.LocalVideoTrack.stop(LocalVideoTrack.kt:135)
  at io.livekit.android.room.participant.LocalParticipant.cleanup(LocalParticipant.kt:938)
  at io.livekit.android.room.Room.cleanupRoom(Room.kt:854)
  at io.livekit.android.room.Room.access$cleanupRoom(Room.kt:68)
  at io.livekit.android.room.Room$handleDisconnect$1.invokeSuspend(Room.kt:836)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
  at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
  at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
  at kotlinx.coroutines.BuildersKt.runBlocking(unavailable:1)
  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
  at kotlinx.coroutines.BuildersKt.runBlocking$default(unavailable:1)
  at io.livekit.android.room.Room.handleDisconnect(Room.kt:828)
  at io.livekit.android.room.Room.disconnect(Room.kt:481)
```

**Comment by davidliu** [comment]
Can you post the full ANR with all the stack threads, not just the locked thread?

**Comment by tuan-jason** [comment]
@davidliu Sure, here's the whole log file then.

[anr_2024-12-09-12-27-37-749.txt](https://github.com/user-attachments/files/18059320/anr_2024-12-09-12-27-37-749.txt)

**Comment by davidliu** [comment]
Resolved over slack, was due to a separate camera track being created alongside ours. Will update documentation to warn against this pitfall.
