### ISSUE TITLE
Error while connecting to server:

### ISSUE THREAD

**Issue by boatt** [livekit/client-sdk-android#566]
javax.net.ssl.SSLException: Unable to parse TLS packet header
                 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:807)
                 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
                 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
                 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
                 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
                 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
                 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
                 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
                 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)

**Comment by davidliu** [comment]
This is happening because you're connecting to a server that doesn't support SSL, likely your local computer which doesn't have SSL certs.

Use the `ws://` protocol for your URL if connecting to a non-SSL server.
